#!/usr/bin/env bash
# Environment setup for aistudio-api.
# Detects host platform and configures project-level dependencies.
#
# On Termux:
#   - Ensures essential Termux packages (uv, ca-certificates, curl, proot-distro).
#   - Generates a local, gitignored ./uv.toml pointing to TUR extra-index
#     to provide prebuilt Android wheels without compilation OOM.
#   - Links system ruff into .venv/bin/ruff if available.
#
# On Desktop / Docker / Linux / macOS / Windows:
#   - Leaves configuration pristine to fetch official PyPI wheels directly.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

log() { printf '[setup-env] %s\n' "$*" >&2; }

is_termux() {
    [[ -n "${PREFIX:-}" && "${PREFIX}" == *"/com.termux"* ]] || command -v pkg >/dev/null 2>&1
}

if is_termux; then
    log "Termux environment detected."

    # 1. Install necessary Termux host packages
    NEEDED_PKGS=()
    for p in ca-certificates curl proot-distro uv; do
        if ! command -v "${p}" >/dev/null 2>&1 && ! dpkg -s "${p}" >/dev/null 2>&1; then
            NEEDED_PKGS+=("${p}")
        fi
    done

    if [[ ${#NEEDED_PKGS[@]} -gt 0 ]]; then
        log "Installing missing Termux packages: ${NEEDED_PKGS[*]}"
        pkg update -y
        pkg install -y "${NEEDED_PKGS[@]}"
    fi

    # 2. Write project-local uv.toml (gitignored) for TUR extra-index
    UV_CONFIG="${PROJECT_ROOT}/uv.toml"
    cat > "${UV_CONFIG}" <<'EOF'
# Auto-generated by scripts/setup-env.sh for Termux
# Directs uv to resolve prebuilt Android wheels from TUR without compilation.
[[index]]
name = "tur"
url = "https://termux-user-repository.github.io/pypi/"
extra = true
EOF
    log "Configured local ${UV_CONFIG} with TUR index."

    # 3. Optional: link precompiled ruff into .venv if available
    if command -v ruff >/dev/null 2>&1 && [[ -d "${PROJECT_ROOT}/.venv/bin" && ! -e "${PROJECT_ROOT}/.venv/bin/ruff" ]]; then
        ln -sf "$(command -v ruff)" "${PROJECT_ROOT}/.venv/bin/ruff"
        log "Linked system ruff into .venv/bin/ruff."
    fi

    log "Termux environment ready. Run 'uv sync' to install dependencies."
else
    log "Standard Linux/Desktop/Docker environment detected. No extra platform configuration needed."
fi
